apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: healthcare
spec:
  selector:
    matchLabels:
      app: healthcare
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: annapoornakaradi/health-care:latest
        ports:
        - containerPort: 8080

##########service################

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: HealthCareApp
  ports:
    - port: 80         
      targetPort: 8080  
      nodePort: 30007  
